"""Pack assets into JS files so the editor works when opened straight from disk
(file://), where browsers block fetch() and taint canvases for local files.

Usage:  python3 tools/build_bundle.py
Run it again after adding or changing anything in assets/ or vendor/.
"""
import base64
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "js", "data")

MIME = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".woff2": "font/woff2"}

FONT_FILES = {
    "poppins": "Poppins",
    "montserrat": "Montserrat",
    "lilita-one": "Lilita One",
    "anton": "Anton",
}


def data_url(path):
    ext = os.path.splitext(path)[1].lower()
    with open(path, "rb") as fh:
        return f"data:{MIME[ext]};base64," + base64.b64encode(fh.read()).decode()


def write_js(name, var, value):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w") as fh:
        fh.write(f"// Generated by tools/build_bundle.py. Do not edit by hand.\nwindow.{var} = ")
        json.dump(value, fh, separators=(",", ":"))
        fh.write(";\n")
    print(f"js/data/{name}: {os.path.getsize(os.path.join(OUT, name)) // 1024} KB")


def main():
    images = {}
    for sub in ("photos", "badges"):
        d = os.path.join(ROOT, "assets", sub)
        for f in sorted(os.listdir(d)):
            if os.path.splitext(f)[1].lower() in MIME:
                images[os.path.splitext(f)[0]] = data_url(os.path.join(d, f))
    vectors = {}
    d = os.path.join(ROOT, "assets", "vectors")
    for f in sorted(os.listdir(d)):
        if f.endswith(".svg"):
            vectors[f[:-4]] = open(os.path.join(d, f)).read().strip()
    write_js("assets.js", "BZ_ASSETS", {"images": images, "vectors": vectors})

    fonts = []
    d = os.path.join(ROOT, "assets", "fonts")
    for f in sorted(os.listdir(d)):
        m = re.match(r"(.+)-latin-(\d+)-(normal|italic)\.woff2$", f)
        if m and m.group(1) in FONT_FILES:
            fonts.append({"family": FONT_FILES[m.group(1)], "weight": int(m.group(2)),
                          "style": m.group(3), "src": data_url(os.path.join(d, f))})
    write_js("fonts.js", "BZ_FONTS", fonts)

    lucide = json.load(open(os.path.join(ROOT, "vendor", "lucide", "icons.json")))
    custom = {}
    d = os.path.join(ROOT, "assets", "icons")
    for f in sorted(os.listdir(d)):
        if f.endswith(".svg"):
            s = open(os.path.join(d, f)).read()
            custom[f[:-4]] = re.search(r"<svg[^>]*>(.*)</svg>", s, re.S).group(1).strip()
    write_js("icons.js", "BZ_ICONS", {"custom": custom, "lucide": lucide["icons"], "tags": lucide["tags"]})


if __name__ == "__main__":
    main()
